// <auto-generated />
using System;
using MiTienda.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiTienda.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308203315_ArregloRelacionVentaDireccion")]
    partial class ArregloRelacionVentaDireccion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiTienda.CapaEntidades.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCarrito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.HasKey("IdCarrito");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProducto");

                    b.ToTable("carrito", null, t =>
                        {
                            t.HasCheckConstraint("CK_Carrito_Cantidad", "cantidad > 0");
                        });
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.HasKey("IdCategoria");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("categoria", (string)null);

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Activo = false,
                            Descripcion = "Electrónica",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdCategoria = 2,
                            Activo = false,
                            Descripcion = "Dormitorio",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdCategoria = 3,
                            Activo = false,
                            Descripcion = "Tecnologia",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("clave");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<bool>("Reestablecer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("reestablecer");

                    b.HasKey("IdCliente");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Departamento", b =>
                {
                    b.Property<string>("IdDepartamento")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("idDepartamento")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdDepartamento");

                    b.ToTable("departamento", (string)null);
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDetalleVenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleVenta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("detalleVenta", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleVenta_Cantidad", "cantidad > 0");

                            t.HasCheckConstraint("CK_DetalleVenta_Total", "total >= 0");
                        });
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idDireccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("DireccionCompleta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("direccionCompleta");

                    b.Property<string>("IdDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("idDepartamento")
                        .IsFixedLength();

                    b.Property<string>("IdDistrito")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .HasColumnName("idDistrito")
                        .IsFixedLength();

                    b.Property<string>("IdProvincia")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("idProvincia")
                        .IsFixedLength();

                    b.Property<int>("IdVenta")
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdDistrito");

                    b.HasIndex("IdProvincia");

                    b.HasIndex("IdVenta")
                        .IsUnique();

                    b.ToTable("direccion", (string)null);
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Distrito", b =>
                {
                    b.Property<string>("IdDistrito")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .HasColumnName("idDistrito")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("IdDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("idDepartamento")
                        .IsFixedLength();

                    b.Property<string>("IdProvincia")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("idProvincia")
                        .IsFixedLength();

                    b.HasKey("IdDistrito");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdProvincia");

                    b.ToTable("distrito", null, t =>
                        {
                            t.HasCheckConstraint("CK_Distrito_Departamento_Consistente", "idDepartamento = LEFT(idProvincia, 2)");
                        });
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMarca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.HasKey("IdMarca");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("marca", (string)null);

                    b.HasData(
                        new
                        {
                            IdMarca = 1,
                            Activo = false,
                            Descripcion = "Samsung",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdMarca = 2,
                            Activo = false,
                            Descripcion = "LG",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdMarca = 3,
                            Activo = false,
                            Descripcion = "Sony",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("idCategoria");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("idMarca");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreImagen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nombreImagen");

                    b.Property<decimal>("Precio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("precio");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rutaImagen");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdMarca");

                    b.ToTable("producto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Producto_Precio", "precio >= 0");

                            t.HasCheckConstraint("CK_Producto_Stock", "stock >= 0");
                        });

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Activo = false,
                            Descripcion = "Televisor inteligente de 55 pulgadas",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 1,
                            IdMarca = 1,
                            Nombre = "Smart TV Samsung 55\"",
                            Precio = 799.99m,
                            Stock = 10
                        },
                        new
                        {
                            IdProducto = 2,
                            Activo = false,
                            Descripcion = "Refrigeradora de alta eficiencia",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 1,
                            IdMarca = 2,
                            Nombre = "Refrigeradora LG",
                            Precio = 1199.99m,
                            Stock = 5
                        },
                        new
                        {
                            IdProducto = 3,
                            Activo = false,
                            Descripcion = "Laptop para uso diario",
                            FechaRegistro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 3,
                            IdMarca = 3,
                            Nombre = "Laptop Sony",
                            Precio = 499.99m,
                            Stock = 15
                        });
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Provincia", b =>
                {
                    b.Property<string>("IdProvincia")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .HasColumnName("idProvincia")
                        .IsFixedLength();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("IdDepartamento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .HasColumnName("idDepartamento")
                        .IsFixedLength();

                    b.HasKey("IdProvincia");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("provincia", (string)null);
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("clave");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaRegistro")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<bool>("Reestablecer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("reestablecer");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idVenta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime>("FechaVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaVenta")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("idCliente");

                    b.Property<string>("IdTransaccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("idTransaccion");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("montoTotal");

                    b.Property<int>("TotalProducto")
                        .HasColumnType("int")
                        .HasColumnName("totalProducto");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.ToTable("venta", (string)null);
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Carrito", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Cliente", "oCliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Producto", "oProducto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oCliente");

                    b.Navigation("oProducto");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.DetalleVenta", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Producto", "oProducto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Venta", "oVenta")
                        .WithMany("oDetalleVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oProducto");

                    b.Navigation("oVenta");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Direccion", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Departamento", "oDepartamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Distrito", "oDistrito")
                        .WithMany()
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Provincia", "oProvincia")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Venta", "oVenta")
                        .WithOne("oDireccion")
                        .HasForeignKey("MiTienda.CapaEntidades.Direccion", "IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oDepartamento");

                    b.Navigation("oDistrito");

                    b.Navigation("oProvincia");

                    b.Navigation("oVenta");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Distrito", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Departamento", "oDepartamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Provincia", "oProvincia")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oDepartamento");

                    b.Navigation("oProvincia");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Producto", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Categoria", "oCategoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MiTienda.CapaEntidades.Marca", "oMarca")
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oCategoria");

                    b.Navigation("oMarca");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Provincia", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Departamento", "oDepartamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oDepartamento");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Venta", b =>
                {
                    b.HasOne("MiTienda.CapaEntidades.Cliente", "oCliente")
                        .WithMany("oVentas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("oCliente");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Cliente", b =>
                {
                    b.Navigation("oVentas");
                });

            modelBuilder.Entity("MiTienda.CapaEntidades.Venta", b =>
                {
                    b.Navigation("oDetalleVenta");

                    b.Navigation("oDireccion")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
